### ISSUE TITLE
theme-picker: Appearance.setColorScheme(null) does not typecheck or work on React Native 0.82+

### ISSUE THREAD

**Issue by vantreeseba** [cubicecho/cubeui#82]
Found in telos (Expo, native registry), React Native 0.85.3.

`registry/ui/theme-preference.tsx` follows the system with:

```ts
Appearance.setColorScheme(next === 'system' ? null : next);
```

From React Native 0.82 onward, `ColorSchemeName` is `'light' | 'dark' | 'unspecified'`, and `null` is no longer accepted:

```
src/components/ui/theme-preference.tsx(36,29): error TS2345: Argument of type '"light" | "dark" | null' is not assignable to parameter of type 'ColorSchemeName'.
```

The problem isn't only the type. In 0.85, `Appearance.setColorScheme` passes its argument straight to `NativeAppearance.setColorScheme`, and only `'unspecified'` is treated as "follow the system" (`Libraries/Utilities/Appearance.js`). So on a device, choosing System passes the native module a `null` it no longer expects.

cubeui builds against 0.81.4, where `null` is still the spelling, so its own typecheck passes.

**Suggested fix:** pick the spelling for the installed version, or type the call so it compiles against both. For example, branch on the installed version's spelling. I haven't checked what 0.81's native side does with `'unspecified'`. A consumer on each side of 0.82 in CI would catch the next one.

telos patches its installed copy locally with a comment citing this issue, until a fixed item ships.
